# Generated by Django 3.2.5 on 2021-07-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_uploaded_id',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
