# Generated by Django 3.2.5 on 2021-07-25 05:36

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='doge_address',
            field=models.CharField(default=services.models.get_btc_addr, max_length=48, unique=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='doge_balance',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='eth_address',
            field=models.CharField(default=services.models.get_btc_addr, max_length=48, unique=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='eth_balance',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='lite_address',
            field=models.CharField(default=services.models.get_btc_addr, max_length=48, unique=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='lite_balance',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
    ]
