# Generated by Django 3.2.5 on 2021-07-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_deposit_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='processed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='processed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='asset',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), (
                'Dogecoin', 'Dogecoin'), ('Litecoin', 'Litecoin')], max_length=48),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), (
                'verified', 'Verified'), ('credited', 'Credited')], default='pending', max_length=48),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='asset',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), (
                'Dogecoin', 'Dogecoin'), ('Litecoin', 'Litecoin')], max_length=48),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), (
                'declined', 'Declined'), ('paid', 'Paid')], default='pending', max_length=48),
        ),
    ]
