# Generated by Django 3.2.5 on 2021-07-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210718_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='has_been_verified',
        ),
    ]
